[package]
name = "financisto2bluecoins"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.23"
flate2 = "1.0.25"
log = "0.4.17"
log4rs = "1.2.0"
